name: masinqo_video_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  http: ^1.1.0

  in_app_review: ^2.0.8
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  video_player: ^2.8.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RobotoCondensed
      fonts: 
        - asset: assets/fonts/RobotoCondensed-ExtraBold.ttf
        - asset: assets/fonts/RobotoCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/RobotoCondensed-ExtraLight.ttf
        - asset: assets/fonts/RobotoCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
        - asset: assets/fonts/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
        - asset: assets/fonts/RobotoCondensed-MediumItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Thin.ttf
        - asset: assets/fonts/RobotoCondensed-ThinItalic.ttf

